# .goreleaser.yaml
version: 2

project_name: scribe

before:
  hooks:
    - go mod tidy

builds:
  - id: scribe-linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/scribe/main.go
    binary: scribe
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: scribe-darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    main: ./cmd/scribe/main.go
    binary: scribe
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE

brews:
  - name: scribe
    repository:
      owner: noble-varghese
      name: homebrew-scribe
    homepage: "https://github.com/noble-varghese/scribe"
    description: "A fast and flexible text expander"
    url_template: "https://github.com/noble-varghese/scribe/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    license: "MIT"
    dependencies:
      - name: xorg-server
      - name: libx11
      - name: libxtst
      - name: libpng
      - name: gcc
    install: |
      bin.install "scribe"
    test: |
      system "#{bin}/scribe", "--version"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'