version: 2

project_name: scribe

before:
  hooks:
    - go mod tidy

builds:
  - id: scribe
    env:
      - CGO_ENABLED=1
    main: ./cmd/scribe/main.go
    binary: scribe
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - cmd: codesign -s - "{{ .Path }}"
          output: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE