name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      
      - name: Install Dependencies
        run: |
          brew install libx11 libxtst libpng gcc pkg-config cmake
          brew install automake libtool
      
      - name: Set up environment
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
      
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}