name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libx11-dev xorg-dev libxtst-dev libpng++-dev
          sudo apt-get install -y xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev
          sudo apt-get install -y libxkbcommon-x11-dev libxkbcommon-dev
          sudo apt-get install -y xsel xclip
      
      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install libx11 libxtst libpng gcc
          brew install pkg-config
      
      - name: Set up environment
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            echo "PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig" >> $GITHUB_ENV
          fi
      
      # Only run goreleaser for the final build on macOS
      - uses: goreleaser/goreleaser-action@v4
        if: matrix.os == 'macos-latest'
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}