name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      
      # Install all required dependencies
      - name: Install Dependencies
        run: |
          brew install libx11 libxtst libpng gcc pkg-config cmake
          brew install automake libtool
          
      # Set required environment variables
      - name: Set up environment
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "PATH=/usr/local/opt/gcc/bin:$PATH" >> $GITHUB_ENV
          
      # Explicitly build and install dependencies
      - name: Build Dependencies
        run: |
          go mod download
          cd $(go env GOPATH)/pkg/mod/github.com/go-vgo/robotgo@v0.110.5
          go install
          cd $(go env GOPATH)/pkg/mod/github.com/robotn/gohook@v0.41.0
          go install
      
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}