name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  darwin-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      
      - name: Install Dependencies
        run: |
          brew install libx11 libxtst libpng gcc pkg-config cmake
          brew install automake libtool
      
      - name: Set up environment
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
      
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser.darwin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: darwin-builds
          path: dist/

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libx11-dev xorg-dev libxtst-dev libpng++-dev 
          sudo apt-get install -y xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev
          sudo apt-get install -y libxkbcommon-x11-dev libxkbcommon-dev
          sudo apt-get install -y xsel xclip
      
      - name: Set up environment
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
      
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser.linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}